### ISSUE TITLE
Umbraco.RadioButtonList values not migrated correctly

### ISSUE THREAD

**Issue by michaelchart** [Jumoo/uSyncMigrations#113]
There seems to be a mismatch between the value that uSyncMigrations produces and what Umbraco 9/10/11 expects for a RadioButtonList property. New Umbraco is expecting the text name of the item, whereas it's the index (or Alias?) of the prevalue that's imported. This means that any RadioButtonList properties will show up with no value selected.

When exporting a Umbraco.RadioButtonList property from a v7 site, the value in your `content.config` file is the index of the prevalue item, e.g. `<theme>2</theme>`

The uSync Migrator doesn't change this value, and it's then imported by uSync into your new Umbraco site.

[New Umbraco stores RadioButtonList values as the string value for the item](https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/radiobutton-list). 

In order to upgrade the [RadioButtonList migrator](https://github.com/Jumoo/uSyncMigrations/blob/main/uSync.Migrations/Migrators/Core/RadioButtonListMigrator.cs) to change indexes into string values, we would need access to the data type config/PreValues in the `GetContentValue` method...

**Comment by michaelchart** [comment]
AFAIK, the GetContentValue method is still not provided with the data type config, so there would need to be some work in refactoring to provide this data to this GetContentValue method to make this happen. This hasn't been high priority enough for us to help make these changes yet.

**Comment by KevinJump** [comment]
The Migration context now contains the ability to add custom values (e.g per datatype,content type) so in theory, we could add the values from the config element of the migration to the custom values table. 

```cs
        context.Migrators.AddCustomValues($"radio_{dataTypeProperty.DataTypeAlias}",
            config.Items.ToDictionary(k => k.Id.ToString(), v => (object)v.Value));
```

and then in a `GetContentValue` method

```cs
    public override string? GetContentValue(SyncMigrationContentProperty contentProperty, SyncMigrationContext context)
    {
        var dataTypeAlias = context.ContentTypes.GetDataTypeAlias(contentProperty.ContentTypeAlias,
            contentProperty.PropertyAlias);

        var values = context.Migrators.GetCustomValues($"radio_{dataTypeAlias}");

        // .. code to set value here. 

    }
```

**Comment by ProNotion** [comment]
@KevinJump @leekelleher Should this just work or do we still need to do something because in my current project, my values are still being migrated as integers and therefore not showing on the properties after migration?

**Comment by leekelleher** [comment]
@ProNotion It did work at the time this code got merged in, but I haven't tried it myself since then. 😬

**Comment by ProNotion** [comment]
Thanks @leekelleher I actually can't see any reason why it's not working so need to dig into it a bit further.

**Comment by KevinJump** [comment]
worth double checking, when we (I) split the project up i missed the dependencies, so uSync.Migrations didn't have uSync.Migrations.Migrators ! - now we didn't fully release this version, but if you built it and installed it you might be missingthe migrations so they didn't actually happen - fixed it this week.

**Comment by ProNotion** [comment]
That would make sense 😆 I will check that as I have a feeling I was using my own build to ensure I got this RadioButtonList feature.
