### ISSUE TITLE
Can't migrate uSync Media properties from umbraco v7 to v11

### ISSUE THREAD

**Issue by PeterKvayt** [Jumoo/uSyncMigrations#144]
I'm trying to migrate Megia from umbraco v7.15.1 to v11.3.1 using uSync.Migrations v4.0.0-beta016.
All media migrated well, but some properties were not migrated:
- umbracoBytes
- umbracoExtension
- umbracoHeight
- umbracoWidth

After investigation I found `uSync.Migrations.Handlers.Seven.MediaMigrationHandler` class where setted ignored properties.

Main question: for what we ignoring this properties?

**Comment by KevinJump** [comment]
Hi, 

These properties are ignored because when you save a media item, Umbraco auto genrates them based on the file item . 

So in general we ignore them.

I am not sure what happens during a migration - but in theory if the media items are in the correct location on disk before the import is ran these values should be set (but i have not tested this).

**Comment by PeterKvayt** [comment]
> Hi,
> 
> These properties are ignored because when you save a media item, Umbraco auto genrates them based on the file item .
> 
> So in general we ignore them.
> 
> I am not sure what happens during a migration - but in theory if the media items are in the correct location on disk before the import is ran these values should be set (but i have not tested this).

Thanks for  fast answer!
I migrated a lot of media (22 260 files) but all of them didn't have those properties.
Maybe the problem was that all media files stored in folder which have names like ./123535/file_name.extension, ./35135/file_name.extension, but in umbraco v11.3.1 media stored in ./zxccxzc/file_name.extension so on.

Also to fix this problem I did the following steps:
1. Install uSync.Migrations v4.0.0-beta016
2. In my project add to composing the following code:
```
builder.WithCollectionBuilder<SyncMigrationHandlerCollectionBuilder>()
            .Clear()
            .Add(() => builder.TypeLoader.GetTypes<ISyncMigrationHandler>().Where(x => x.Name != "MediaMigrationHandler"))
            .Add(typeof(MyMediaMigrationHandler));
```
Where `MyMediaMigrationHandler` is custom implementation of `MediaMigrationHandler` where I remove all ignored properties.

One more question: is this solution safety or I can broke some migration pipeline?

**Comment by KevinJump** [comment]
Hi, 

I don't think it will break anything, (and happy to look at removing the ignored values - either by default or config).

The media paths are different for new media when you migrate, but you can infact set the path to anything, so i theory the media folder can be copied over from v7 as it (but into `wwwroot/media`) and then on import the media path will be set and it should be found. 🫰

**Comment by PeterKvayt** [comment]
> The media paths are different for new media when you migrate, but you can infact set the path to anything, so i theory the media folder can be copied over from v7 as it (but into `wwwroot/media`) and then on import the media path will be set and it should be found. 🫰

Yes, I have copied the media folder from v7 to v11(we use azure blob storage, but for local it works too) without any changes and it found all media as expected.

> I don't think it will break anything, (and happy to look at removing the ignored values - either by default or config).

It's good to know that it will not break anything. 
Did you mean that good approach is to move ignoring properties to config?

**Comment by KevinJump** [comment]
Yeah - I think we could have a configuration setting - of `SetAllMediaProperties` or something that when its set to true, we do set everything, and when its false we do what we do now. 

can be simple or complex, but a way of turning it on/off would make it so you didn't need custom code, but we could have the other behaviour (if we need it).

**Comment by PeterKvayt** [comment]
Yeah, I think it's a good approach. I will think about it, If I will have some free time, maybe I will create a pull request.

Thanks a lot for help!

Now I'm testing my solution, if all migrated fine, I will close issue!

Good luck!

**Comment by ProNotion** [comment]
@KevinJump @PeterKvayt  This was closed but did anything ever get done about it? I've got a huge media library that gets migrated with no image dimensions at all.

**Comment by KevinJump** [comment]
I haven't looked at this in a while I think the key  might be to have the media file in place before the migration of the media items takes place? 

When the media is saved inside umbraco if there is media on disk then the properties are auto generated by Umbraco (i think). 

It might be that the migration doesn't trigger this auto generation, and there is something to be added there, one way might be to use either the uSync or Umbraco events, that happen (so ItemImported or MediaSaved) to trigger it, but i am not 100% what exectly it would be triggering (i am assuming here it isn't already triggered if the media files are in place.)

**Comment by ProNotion** [comment]
@KevinJump Having the media files in place is a blocker for me, I want to migrate the existing property data. The reason is that the site I am working on has an enormous media library and it's just not practical for me to clone their entire media library for this purpose. Even with that reason aside I think it would make sense to copy the existing values in the migration then if they are updated later on by Umbraco so be it but at least there are values there initially. 

For now, I think I am going to have to just comment out this block:

```
_ignoredProperties.UnionWith(new[]
{
    UmbConstants.Conventions.Media.Bytes,
    UmbConstants.Conventions.Media.Extension,
    UmbConstants.Conventions.Media.Height,
    UmbConstants.Conventions.Media.Width,
});
```

I will then have to use a custom build of the `uSyncMigrations` project but it would be good to get something into the project to allow control of this. I just can't understand at the moment how to pass some config into the `MediaMigrationHandler` to allow it to be enabled/disabled.
