### ISSUE TITLE
Error in GUID parsing for related links & related links 2 datatype

### ISSUE THREAD

**Issue by drummerboy46** [Jumoo/uSyncMigrations#145]
@KevinJump  I have a ton of related links content that have guids in various places within the captions and links themselves, see screenshot.

![image](https://github.com/Jumoo/uSyncMigrations/assets/6703035/d15ab548-924a-4b5b-bcd9-5bb094fc6b9d)

The parser isn't quite clever enough to capture the correct portion of the Json and ensure only "link" and "internal" Guids are encapsulated in quotes to create valid Json.

Suggested improvement (as yet untested)

 private string WrapGuidsWithQuotes(string value)
    {       
      string guidRegEx = @"(""internal""|""link""):(\b[A-Fa-f0-9]{8}(?:-[A-Fa-f0-9]{4}){3}-[A-Fa-f0-9]{12}\b)";
        HashSet<string> uniqueMatches = new HashSet<string>();

        foreach (Match m in Regex.Matches(value, guidRegEx)) {
            uniqueMatches.Add(m.Groups[1].Value);
        }

        foreach (var guid in uniqueMatches) { 
          value = value.Replace(guid, "\"" + guid + "\"")
                .Replace("\"\"", "\"");
        }
        return value;
    }

**Comment by KevinJump** [comment]
Yeah - i suspect it needs a little looking at and cleaning up & It looks very similar to a bit of code we have somewhere else in the migrations package.

**Comment by drummerboy46** [comment]
@KevinJump I've cloned the project and fixed this, do I fork to submit a pull request?

**Comment by KevinJump** [comment]
yep - If you can, a fork will then let you create a PR. and we will merge it in.

**Comment by KevinJump** [comment]
Fixed in phase 4
