### ISSUE TITLE
uSync Migrations Packer 7 ouput file not read by Linux

### ISSUE THREAD

**Issue by craigs100** [Jumoo/uSyncMigrations#210]
uSync Migrations Packer V7 installed and produced a zip file. Moved zip file from Win 10 VM to Linux for import into new site. 

uSync Migrations Uploads the zip file but doesn't fill in any of the data under Migration Details, Folder Locations & Info. 

If I unzip the file locally and point the Select Source at their folder I get "Unsupported or undetected version"

I can see the individual files hold what looks to be the right data for the content, I just can't import them!  The files aren't extracted to folders, their names are of the form site\views\Partials\Navigation\NestedSiteMap.cshtml.

Just tried it on the Win VM and it unpacks the zip fine there, so maybe a typo somewhere?? 😉

**Comment by craigs100** [comment]
Bump : Package is still at V7.0.1 and not working so can't choose correct migration plan manually. It's a big issue on sites with loads of Nested Content.

**Comment by KevinJump** [comment]
Hi, Sorry took a while. 

We have merged the v7 and v8 packer code base, to make this easier to manage. 
https://github.com/Jumoo/uSync.Migrations.Packers

and we have updated the downloadable packer for v7 to v7.1.0.
https://clients.jumoo.co.uk/migrations/uSync.Migrations.Packer.v7_v7.1.0.zip
this one does save the zip files with Linux path deviders.

**Comment by craigs100** [comment]
With (uSync.BackOffice 4.0.15.0) (uSync.Core 6.0.15.0) [uSync.Content: 4.1.9.1] [Migration.Packer: 1.0.0]

This new version (7.1.0) doesn't work on the V7.15.10 site at all. As soon as I navigate to the Developer section I get the error:-
```Request error: The URL returned a 404 (not found):
/app_plugins/uSync.Content/uSyncDashboardContent.html```

Then in the uSync BackOffice tab the Content and Migrations tabs are totally empty and there is no Migrations folder in the uSync folder. I have restarted the site several times and performed several full exports.
