### ISSUE TITLE
RJP migration fails if content target deleted or trashed item.

### ISSUE THREAD

**Issue by bielu** [Jumoo/uSyncMigrations#220]
So had really interesting issue with migration, I noticed if item which is linked in RJP migration for multinode tree picker works fine, but there is usync issue afterword and cause item to not be populated in content.

@KevinJump not sure if I should search fix in Migrations or in Usync 🤔 as it fails already post migration on import to umbraco via usync

**Comment by KevinJump** [comment]
I supose it depends a bit. 

If the file created by migrations isn't quite right, and uSync then can't import it correctly, i would say migrations needs to be fixed, if however you can produce the exact same file with a uSync process on one site and it doesn't import on another then its a uSync issue.

If this is an issue with things inside blockgrid then upgrade uSync and see if that helps, as uSync now processes the nested json slightly cleaner _- in that it makes it all json and then makes it escaped json where Umbraco needs it to be escaped_

**Comment by bielu** [comment]
Hmm didnt try reproduce it on Usync yet, will try in next few days, but yeah to make it work in usync migrations, we would need access context and validate if UDI exist and if not remove property of subject. So far I noticed it happens on block editor, so will try do minimal reproduction on clear v10 with Usync and if I will be able I will make fix for both usync and migration :)

**Comment by bielu** [comment]
Okay so was able to reproduce issue on usync:
-> use Multinode treep picker in block
-> select page
-> remove page (fully)
and usync file still contains deleted node and cannot be imported 🤔

**Comment by KevinJump** [comment]
Hi, Can you open a uSync issue - I would move the ticket, but they are in different orgs on github :( 

I think its a good hacktoberfest fix for uSync this one.
