### ISSUE TITLE
Phase 4.1 doesn't seem to be running all the migrators

### ISSUE THREAD

**Issue by stevetemple** [Jumoo/uSyncMigrations#245]
After many hours of pulling my hair out trying to get a custom migrator working, I've realised that version phase 4.1 isn't converting any content using the migrators, it's doing the ContentTypes but not actual content values. It wasn't just my migrator but all of them not updating the content values.

Rolling back to an older version (3) and it's working correctly now

**Comment by KevinJump** [comment]
OK, Stupid error no 412. 

Since we split it all up - The uSync.Migrations.Migrator package is not listed as a depenency of uSync.Migrations.

so on a clean install you get no migrators ! 

fix done. will push a new version later.

**Comment by stevetemple** [comment]
It's a bit interesting because I'd downloaded the repo and included the migrators in the project directly. I could see it was running the `GetConfigValues` method but not the `GetContentValue` methods. So might be something else also going on.

**Comment by ProNotion** [comment]
That might also explain [the issue I am seeing here](https://github.com/Jumoo/uSyncMigrations/issues/113#issuecomment-1824054633)

**Comment by stevetemple** [comment]
Yeah I think so, it's something in the code that now allows per property migrators is now not including the general migrators. I'll try and dig in further. 

It's a lot higher in the stack than the actual place where it should be calling GetContentValue. More in the setup of the migrators

**Comment by ProNotion** [comment]
I'm still trying to unravel this but the list of DataType aliases in the `ContentTypeMigrationContext` all have empty values which is quite possible related.

**Comment by stevetemple** [comment]
That looks promising

**Comment by stevetemple** [comment]
That looks like it's fixed it when I run it now, good spot on that one @ProNotion

**Comment by stevetemple** [comment]
This is fixed in latest source
