### ISSUE TITLE
Property culture variant on document types are no longer culture variants after migration

### ISSUE THREAD

**Issue by FrederikSorensen** [Jumoo/uSyncMigrations#246]
Document type properties are missing their "vary by culture" setting after migration.

Variations in the config file seems to always set it's value to "Nothing" when the property is "vary by culture".

Screenshots for visual clarification:
![migration data](https://github.com/Jumoo/uSyncMigrations/assets/14737789/045cfda5-a0be-4f3f-ac2c-338996a28137)
![usync data](https://github.com/Jumoo/uSyncMigrations/assets/14737789/c4ffa12c-d1ad-4258-8416-92461c08a831)

**Comment by KevinJump** [comment]
yeah - we don't 100% support migrating vary values (that is we do, but some of the advanvced migrations don't yet work with it). 

but this is fixed now in #248

**Comment by FrederikSorensen** [comment]
Cheers! 

Looking forward to test it.
Any idea on when you will release a new version with this fix?

**Comment by FrederikSorensen** [comment]
Just tested it locally, works like a charm.

Thanks a lot @KevinJump!

**Comment by KevinJump** [comment]
Finally! a Phase 5 release includes this 
https://github.com/Jumoo/uSyncMigrations/releases/tag/4.0.0-phase.5
