### ISSUE TITLE
Idea: Enhancements for SyncMigrationContext

### ISSUE THREAD

**Issue by soreng** [Jumoo/uSyncMigrations#40]
Hi,

I've been trying out uSyncMigrations for the last few days, and the out-of-the box experience is great.

To support som very old (homemade) property editors I had to create something to map from a content ID (int) to a content Key (Guid). This was done a bit hard, with a class like this:

```
internal class SyncPropertyWithIdMigrator : SyncPropertyMigratorBase
{
    private readonly Dictionary<int, Guid> _idToKey = new();
    
    private readonly IOptions<MigrationOptions> _migrationOptions;

    protected SyncPropertyWithIdMigrator(IOptions<MigrationOptions> migrationOptions)
    {
        _migrationOptions = migrationOptions;
    }

    protected Guid? GetMediaKeyFromId(int id) => GetKeyFromId(id, "media");

    protected Guid? GetContentKeyFromId(int id) => GetKeyFromId(id, "content");

    private Guid? GetKeyFromId(int id, string folder)
    {
        if (_idToKey.TryGetValue(id, out var key))
        {
            return key;
        }

        var source = Path.Combine(_migrationOptions.Value.Source, folder);
       
        var files = Directory.EnumerateFiles(source, "*.config", SearchOption.AllDirectories);

        foreach (var path in files)
        {
            var content = XElement.Load(path);

            if (id != content.Attribute("id").ValueOrDefault(default(int)))
            {
                continue;
            }

            var guid = content.Attribute("guid").ValueOrDefault(Guid.Empty);

            if (guid == Guid.Empty)
            {
                continue;
            }
            
            _idToKey[id] = guid;

            return guid;
        }

        return null;
    }

}
```

In this case it would have helped if it was possible to have some more information in the the path to the migration source, since it can differ from the injected options. I tried to look into the services exposed, if there was a way to read the migration folder, but it doesn't look like there is any information available about a specific migration (ie the path to the xml files).

I think that populating an id-to-key dictionary would be helpfull for a lot of these very old sites.

Another way to implement it, could be to add another notication type like `SyncMigrationStartingNotification`, that could hold information about the sourcefiles, the handler type (content, media etc), and then maybe expose an "AdditionalData" dictionary on `SyncMigrationContext` to allow the data to be stored.

**Comment by leekelleher** [comment]
@soreng My initial thought is that the IDs `int` to `Guid` could (or should) be resolved prior to the migration, so on the v7 side, (along the lines of "uSync doing what it does best"). e.g. to have a custom `IContentMapper` for your custom property-editors; here's an example of RJP Url Picker in the v7 uSync codebase: <https://github.com/KevinJump/uSync-Legacy/blob/v4_master/Jumoo.uSync.ContentMappers/RJPMapper.cs>

But I also appreciate that might not be easy or straight forward to put in place on a legacy project. An `int`/`Guid` lookup in the `SyncMigrationContext` could be useful. 🤔😃

**Comment by KevinJump** [comment]
v7 usync should in theory have the information in it's XML files for us to map IDs to GUIDs but it depends on the properties, I think we might be able to do something, will take a look this week.
