### ISSUE TITLE
Feature: Move all 'lookup' requirements into the context

### ISSUE THREAD

**Issue by KevinJump** [Jumoo/uSyncMigrations#45]
Make it so you can do all lookups via the context, and we can then decide there what is a dictionary and what is a service call, removing the service dependencies from migrators #44

**Comment by leekelleher** [comment]
I'm wondering if we need to do any post-migration clean up with the `SyncMigrationContext` instance afterwards? Whether it needs to be `IDisposable` or not? _(I dunno, just don't wanna leave an object with a bunch of potentially large dictionaries lingering around in memory)._

**Comment by KevinJump** [comment]
Closing this, might open a 'clean up context' issue, but i am not sure - everything (the lists) is Internal at the moment - so extension methods isn't cleaner, it might just be naming conventions and organisation of the file that is needed.
