### ISSUE TITLE
Archetype

### ISSUE THREAD

**Issue by runegronkjaer** [Jumoo/uSyncMigrations#77]
Is it correct that there is no Archetype migrator?
If there's none, which migrator would be best to use as an example if we should implement it ourselves?

/Rune

**Comment by soreng** [comment]
hi @runegronkjaer 

The NestedContent or StackedContent should be some good candidates for this. I do belive you already have had some experience with create a LeBlender migrator, but that is more inline with the DTGE migrator.

You could create a PR if you need help on some code :)

**Comment by KevinJump** [comment]
We have merged an Archetype migrator this week https://github.com/Jumoo/uSyncMigrations/pull/105 - we haven't packed it all into a release yet - but we should soon.
